base_path: record/20260629_182416_badnet_attack_badnet_6MrG

# Model to evaluate
# model_name: mnist_patch_low_asr_model.pth
model_name: final_state_dict.pth

# ------------------------------------------------------------
# Dataset
# ------------------------------------------------------------
dataset: mnist
dataset_path: ./data
# ------------------------------------------------------------
# Model
# ------------------------------------------------------------
model: simplecnn
num_classes: 10
# ------------------------------------------------------------
# Image
# ------------------------------------------------------------
input_height: 28
input_width: 28
mean: 0.5
std: 0.5
random_crop_padding: 4
# ------------------------------------------------------------
# Trigger
# ------------------------------------------------------------
trigger_path: ./resource/badnet/trigger_image.png
# ------------------------------------------------------------
# Evaluation
# ------------------------------------------------------------
batch_size: 128
num_workers: 4
target_label: 0
# ------------------------------------------------------------
# Runtime
# ------------------------------------------------------------
device: cuda
